eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
logging:
    level:
        org:
            springframework:
                cloud:
                    gateway: TRACE
                    gateway.route.RouteDefinitionLocator: INFO
        root: info
management:
    tracing:
        sampling:
            probability: 1.0
server:
    port: 8084
spring:
    application:
        name: gateway
    cloud:
        gateway:
            routes:
            -   id: company_service
                predicates:
                - Path=/companies/**
                uri: lb://COMPANY-SERVICE
            -   id: job_service
                predicates:
                - Path=/jobs/**
                uri: lb://JOB-SERVICE-DEV
            -   id: review_service
                predicates:
                - Path=/reviews/**
                uri: lb://REVIEW-SERVICE
            -   filters:
                - SetPath=/
                id: eureka-server
                predicates:
                - Path=/eureka/main
                uri: http://localhost:8761
            -   id: eureka-server-static
                predicates:
                - Path=/eureka/**
                uri: http://localhost:8761
